### ISSUE TITLE
"times" icon not included in font

### ISSUE THREAD

**Issue by slavkoja** [juehv/kanboard-InstantActions#2]
After i install this, the "close" action has not icon. It seems, that the "times" is included only in pro version of FontAwesome, not in the one distributed with Kanboard.

**Comment by juehv** [comment]
Can you provide a screenshout?
Also can you check if they changed something in their distribution from 1.2.0 to the current version (since it works for us in the distributed version)?

**Comment by slavkoja** [comment]
After same research, i see that i was wrong. The icon is in free, but it is not shown in FF, at least not in FF 60 ESR (linux), see attached screenshot from their page: ![fa-times](https://user-images.githubusercontent.com/5506544/54236352-9ea7c100-4513-11e9-8c45-a60c1d8edec3.png)

**Comment by juehv** [comment]
Well on my linux system with FF it works just fine... You can change the icon to "times-circle" and send me a PR if you like. 
Cheers!

**Comment by slavkoja** [comment]
I found the reason, i have forced to use FF's fonts instead document's fonts:
```
browser.display.use_document_fonts;0
```
But i still do not understand, why only some icons are missing...

**Comment by juehv** [comment]
Ok at least it's fixed for now :)
