### ISSUE TITLE
Unable to load this plugin class: \Kanboard\Plugin\kanboard-InstantActions\Plugin

### ISSUE THREAD

**Issue by bash-stack** [juehv/kanboard-InstantActions#5]
after update to most recent kanboard, the log says

`[critical] kanboard-InstantActions: Unable to load this plugin class: \Kanboard\Plugin\kanboard-InstantActions\Plugin`
over and over

**Comment by Seth401** [comment]
What worked for me is fixing the case for the mentions of `InstantActions`. It might also work to rename the plugin folder to `Instantactions` and/or namespace.

See e.g. [Plugin.php](https://github.com/juehv/kanboard-InstantActions/blob/92cabf0f2aa0b037d58c94683b147ca440cd2797/Plugin.php#L17), [settings.php](https://github.com/juehv/kanboard-InstantActions/blob/92cabf0f2aa0b037d58c94683b147ca440cd2797/Template/settings.php#L12) and quite a few more places. See how the [namespace](https://github.com/juehv/kanboard-InstantActions/blob/92cabf0f2aa0b037d58c94683b147ca440cd2797/Plugin.php#L3) is capitalized. I am not sure whenever it's the name of the namespace or the folder but changing `Instantactions` to `InstantActions` worked for me.
